### ISSUE TITLE
Customer Shipping Address Update/Creation

### ISSUE THREAD

**Issue by hobkirkweb** [stripe/stripe-postman#17]
When using update a customer the shipping[address] is shown as {"line1":"<string>","city":"<string>","country":"<string>","line2":"<string>","postal_code":"<string>","state":"<string>"} in the example.

This returns an error 

{
    "error": {
        "message": "Invalid object",
        "param": "shipping[address]",
        "type": "invalid_request_error"
    }
}

I could only get it to work by creating new keys:

shipping[address][line1] <string>
shipping[address][line2] <string>
shipping[address][city] <string>
shipping[address][country] <string>
shipping[address][postal_code] <string>
shipping[address][state] <string>

Am I missing something in the way it is shown in the example

Andy

**Comment by charlesw-stripe** [comment]
Hey @hobkirkweb, thanks for reporting this issue.  `shipping[address]` is a nested field and so the Postman collection should include child parameters like `shipping[address][line1]`. We're working on remediating this and should have an updated Postman Collection soon!
